---
title: "Final Project"
author: "Your Name"
date: "2025-01-01"
format:
  html:
    code-fold: true
    toc: true
---

**Intro**
movies are a hot topic among people and companies, people because they dont want to pay to see garbage and companies because they want more viewwer and beter reviews. with this in mind we took data from disney movies and ran analasis to find if thre was ny high prodicters of ether revenue or reviews,(from criticts for awards, and from audeances for revinue). 
to d this analasis we first needed data and wanted to colect it leagaly and with out becoming a digital nucance, we fallowed the web sctaping requierments posted on the web sights (\robots) to ensure both where requerments wehre met.
**Summary**
to get the data we first needed a list of movies form disney, we wcraped this form a wiki page, then took our list to a rating websight, we used rottontomatow, and found the patern and frak=nkenstined the Url from the parts needed (name of movie) and the URL form the websight we needed (rotentomatos). after than we inspected teh page to get the sections we need form that and wraped it in a for loop to get it all.
tehan we analsied it.

**EDA**
477 movies whre used in this analasis, there where some missing values in difrent colums and so some data is exuded form difrent analasises.
mean audeance rating = 61
sd audance ratings = 19
mean critict rating = 62
sd critict ratings =27
coralations (audeance score, critict score) = 0.72
mean revinue = 83668368.59
points of intrest:
  -R rated movies earn significantly less than any   other movie
  -PG-13 movies earn more than any other 
  -the critict scores and pupulation score are closer related in the lst 25 years
  -the vareance of revinue in the last 25 years has become more extream
  -the number of directers in recent years looks to be inversly coralated (more analasis needed)
  
  **link to websight rotton tomataoes**
  [rotentomatoes websight](https://editorial.rottentomatoes.com/guide/140-essential-action-movies-to-watch-now/)

  **link to github with analasis and data**
  [github](https://github.com/CNelson2004/Movies_Analysis)